# Monument pool derived from the images/ folder.
# Coordinates are taken from monuments-list.md.
# imageUrl points to /images/<filename> served as static assets.
MONUMENTS = [
    {
        "id": "big-ben",
        "name": "Big Ben",
        "country": "United Kingdom",
        "latitude": 51.500786,
        "longitude": -0.124681,
        "imageUrl": "/images/BigBen_London.jpg",
        "imageAttribution": "",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "celsus-library",
        "name": "Librairie de Celsus",
        "country": "Turkey",
        "latitude": 37.939381,
        "longitude": 27.340000,
        "imageUrl": "/images/Celsus_Library.jpg",
        "imageAttribution": "",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "chichen-itza",
        "name": "Chichen Itza",
        "country": "Mexico",
        "latitude": 20.682985,
        "longitude": -88.568649,
        "imageUrl": "/images/ChichenItza.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "christ-king-poland",
        "name": "Statue Jésus Christ le roi",
        "country": "Poland",
        "latitude": 52.236590,
        "longitude": 15.546670,
        "imageUrl": "/images/Christ_Poland.jpg",
        "imageAttribution": "",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "christ-the-redeemer",
        "name": "Christ le rédempteur",
        "country": "Brazil",
        "latitude": -22.951660,
        "longitude": -43.210830,
        "imageUrl": "/images/Christ_the_Redeemer_Rio.jpg",
        "imageAttribution": "",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "colosseum",
        "name": "Colisée de Rome",
        "country": "Italy",
        "latitude": 41.890221,
        "longitude": 12.492348,
        "imageUrl": "/images/Coliseum_Roma.jpg",
        "imageAttribution": "",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "fribourg-cathedral",
        "name": "Cathédrale Saint-Nicolas de Fribourg",
        "country": "Switzerland",
        "latitude": 46.806100,
        "longitude": 7.161970,
        "imageUrl": "/images/Fribourg_Cathedral.jpg",
        "imageAttribution": "",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "india-gate",
        "name": "Porte de l'Inde",
        "country": "India",
        "latitude": 28.612912,
        "longitude": 77.229506,
        "imageUrl": "/images/IndiaGate_India.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "meroe-pyramids",
        "name": "Pyramides de Méroé",
        "country": "Sudan",
        "latitude": 16.937600,
        "longitude": 33.751300,
        "imageUrl": "/images/Meroe_Soudan_Pyramids.jpg",
        "imageAttribution": "",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "moai-statues",
        "name": "Statues Moai de l'île de Pâques",
        "country": "Chile (Easter Island)",
        "latitude": -27.121200,
        "longitude": -109.366400,
        "imageUrl": "/images/Moai_PagIsland.jpg",
        "imageAttribution": "",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "mont-saint-michel",
        "name": "Mont Saint-Michel",
        "country": "France",
        "latitude": 48.636080,
        "longitude": -1.511490,
        "imageUrl": "/images/MontStMichel_France.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "saint-basils-cathedral",
        "name": "Cathédrale Saint-Basile",
        "country": "Russia",
        "latitude": 55.752523,
        "longitude": 37.623087,
        "imageUrl": "/images/Moscow_Kremlin.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "mount-rushmore",
        "name": "Mont Rushmore",
        "country": "United States",
        "latitude": 43.879102,
        "longitude": -103.459067,
        "imageUrl": "/images/Mount_Rushmore_US.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "parthenon",
        "name": "Parthenon",
        "country": "Greece",
        "latitude": 37.971532,
        "longitude": 23.726749,
        "imageUrl": "/images/Pantheon_Athens.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "senso-ji",
        "name": "Temple de Senso-ji",
        "country": "Japan",
        "latitude": 35.714765,
        "longitude": 139.796655,
        "imageUrl": "/images/Senso_Ji_Tokyo.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "great-sphinx",
        "name": "Grande Sphinx de Gizeh",
        "country": "Egypt",
        "latitude": 29.975299,
        "longitude": 31.137496,
        "imageUrl": "/images/Sphynx_Egypt.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "statue-of-liberty",
        "name": "Statue de la Liberté",
        "country": "United States",
        "latitude": 40.689249,
        "longitude": -74.044500,
        "imageUrl": "/images/Statue_Of_Liberty_NewYork.jpg",
        "imageAttribution": "",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "taj-mahal",
        "name": "Taj Mahal",
        "country": "India",
        "latitude": 27.175015,
        "longitude": 78.042155,
        "imageUrl": "/images/TajMahal_India.jpg",
        "imageAttribution": "",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "sydney-opera-house",
        "name": "Opéra de Sydney",
        "country": "Australia",
        "latitude": -33.856784,
        "longitude": 151.215297,
        "imageUrl": "/images/Theater_Sydney.png",
        "imageAttribution": "",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "tokyo-tower",
        "name": "Tour de Tokyo",
        "country": "Japan",
        "latitude": 35.658581,
        "longitude": 139.745433,
        "imageUrl": "/images/Tokyo_Tower.jpg",
        "imageAttribution": "",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "palau-arts-valencia",
        "name": "Palais des Arts de Valence",
        "country": "Spain",
        "latitude": 39.460661,
        "longitude": -0.356544,
        "imageUrl": "/images/Valencia_ArtsPalace.jpg",
        "imageAttribution": "",
        "difficulty": 3,
        "active": True,
    },
]

MONUMENTS_BY_ID = {m["id"]: m for m in MONUMENTS}


def get_active_monuments():
    return [m for m in MONUMENTS if m["active"]]


def get_monument_by_id(monument_id):
    return MONUMENTS_BY_ID.get(monument_id)
