# Curated monument pool for the MVP.
# Image URLs use Wikimedia Commons' Special:FilePath redirect for stable, hotlink-friendly access.
MONUMENTS = [
    {
        "id": "eiffel-tower",
        "name": "Eiffel Tower",
        "country": "France",
        "latitude": 48.8584,
        "longitude": 2.2945,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Eiffel_Tower_from_the_Tour_Montparnasse_3,_Paris_June_2010.jpg",
        "imageAttribution": "Benh LIEU SONG, CC BY-SA 3.0, via Wikimedia Commons",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "statue-of-liberty",
        "name": "Statue of Liberty",
        "country": "United States",
        "latitude": 40.6892,
        "longitude": -74.0445,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Statue_of_Liberty_7.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "colosseum",
        "name": "Colosseum",
        "country": "Italy",
        "latitude": 41.8902,
        "longitude": 12.4922,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Colosseo_2020.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "great-pyramid-giza",
        "name": "Great Pyramid of Giza",
        "country": "Egypt",
        "latitude": 29.9792,
        "longitude": 31.1342,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Kheops-Pyramid.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "taj-mahal",
        "name": "Taj Mahal",
        "country": "India",
        "latitude": 27.1751,
        "longitude": 78.0421,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Taj_Mahal_(Edited).jpeg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "big-ben",
        "name": "Big Ben",
        "country": "United Kingdom",
        "latitude": 51.5007,
        "longitude": -0.1246,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Big_Ben_2014.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "sydney-opera-house",
        "name": "Sydney Opera House",
        "country": "Australia",
        "latitude": -33.8568,
        "longitude": 151.2153,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Sydney_Opera_House_Sails_Edit02.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 1,
        "active": True,
    },
    {
        "id": "christ-the-redeemer",
        "name": "Christ the Redeemer",
        "country": "Brazil",
        "latitude": -22.9519,
        "longitude": -43.2105,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Christ_the_Redeemer_-_Cristo_Redentor.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "machu-picchu",
        "name": "Machu Picchu",
        "country": "Peru",
        "latitude": -13.1631,
        "longitude": -72.5450,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Machu_Picchu,_Peru.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "petra",
        "name": "Petra (Al-Khazneh)",
        "country": "Jordan",
        "latitude": 30.3285,
        "longitude": 35.4444,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Al_Khazneh_Petra_Jordan.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "mount-rushmore",
        "name": "Mount Rushmore",
        "country": "United States",
        "latitude": 43.8791,
        "longitude": -103.4591,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Rushmore_detail_view_(100MPix).jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "stonehenge",
        "name": "Stonehenge",
        "country": "United Kingdom",
        "latitude": 51.1789,
        "longitude": -1.8262,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Stonehenge2007_07_30.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "angkor-wat",
        "name": "Angkor Wat",
        "country": "Cambodia",
        "latitude": 13.4125,
        "longitude": 103.8670,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Angkor_Wat_temple.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 3,
        "active": True,
    },
    {
        "id": "chichen-itza",
        "name": "Chichen Itza",
        "country": "Mexico",
        "latitude": 20.6843,
        "longitude": -88.5678,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Chichen_Itza_3.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
    {
        "id": "neuschwanstein-castle",
        "name": "Neuschwanstein Castle",
        "country": "Germany",
        "latitude": 47.5576,
        "longitude": 11.1014,
        "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_Neuschwanstein_2013.jpg",
        "imageAttribution": "Wikimedia Commons contributors, CC BY-SA",
        "difficulty": 2,
        "active": True,
    },
]

MONUMENTS_BY_ID = {m["id"]: m for m in MONUMENTS}


def get_active_monuments():
    return [m for m in MONUMENTS if m["active"]]


def get_monument_by_id(monument_id):
    return MONUMENTS_BY_ID.get(monument_id)
